### ISSUE TITLE
Normal(mu,sigma) is the parameterization

### ISSUE THREAD

**Issue by jverzani** [roualdes/plutonotebooks#1]
Nice repository. I look forward to incorporating your ideas to speed these things up. In browsing your Normal notebook, I noticed you are calling `Normal(mu,sigma^2)`. I'm pretty sure the parameterization chosen in Distributions  is by `sigma`, not the variance. https://juliastats.org/Distributions.jl/stable/univariate/#Distributions.Normal

**Comment by roualdes** [comment]
Thanks, @jverzani!
